server:
  port: 2000
eureka:
  instance:
    hostname: uuid
    appname: 注册中心
  client:
    registerWithEureka: false # 单点的时候设置为 false 禁止注册自身
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:2000/eureka
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 4000
logging:  
  level:  
    org.springframework.cloud.gateway: trace