server:
  port: 9900
 
spring:
  application:
    name: gateway
  cloud:
      gateway:
        discovery:
          locator:
            enabled: false
            #开启小写验证，默认feign根据服务名查找都是用的全大写
            lowerCaseServiceId: true
        routes:
        - id: lancet_router
          uri: lb://LANCET
          predicates:
            - Path=/lancet/**
          filters:
            - StripPrefix=1

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:2000/eureka/
      
logging:  
  level:  
    org.springframework.cloud.gateway: trace